version: '3.7'

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - api_network
networks:
  api_network:
    external:
      name: mnet
