version: '3.7'

services:
  mongo:
    image: mongo:4.1.4-xenial
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - api_network
    volumes:
      - ../../data/db-mongo:/data/db
      - ./dockers/mongo/mongod.conf:/etc/mongod.conf
    # command: mongod --dbpath /data/db
networks:
  api_network:
    external:
      name: mnet
