version: '3'
services:
  mongo:
      image: mongo:4.1.4-xenial
      container_name: db-mongo
      hostname: mongo
      restart: always
      ports:
        - "27017:27017"
      # networks:
      #   - api_network
      volumes:
        - ../../data/db-mongo:/data/db
        - ./dockers/mongo/mongod.conf:/etc/mongod.conf
      # command: mongod --dbpath /data/db
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 9091:8081
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo
    links:
      - mongo
  sso:
    image: "tripbff/sso"
    ports:
      - "3000:80"
    # networks:
    #   - api_network
    environment: # read from .env file
      - SERVER_HOST=localhost
      - SERVER_PORT=80
      - REDIS_HOST=192.168.1.4
      - REDIS_PORT=6379
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
  trip-api:
    image: "tripbff/trip-api"
    ports:
      - "8000:80"
    # networks:
    #   - api_network
    environment: # read from .env file
      - SERVER_HOST=localhost
      - SERVER_PORT=80
      - REDIS_HOST=192.168.1.4
      - REDIS_PORT=6379
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
# networks:
#   api_network:
#     external:
#       name: mnet
