version: '3'
services:
  mongo:
      image: mongo:4.1.4-xenial
      container_name: tripbff-mongo
      hostname: mongo
      restart: always
      ports:
        - "27017:27017"
      # networks:
      #   - api_network
      volumes:
        - ../../data/db-mongo:/data/db
        - ./dockers/mongo/mongod.conf:/etc/mongod.conf
      # command: mongod --dbpath /data/db
  redis:
    image: redis
    restart: always
    container_name: tripbff-redis
    ports:
      - 6379:6379
    volumes:
     - /tmp:/data
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 9091:8081
  #   # environment:
  #     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     # ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo
# networks:
#   api_network:
#     external:
#       name: mnet
